FROM ollama/ollama:latest
# use 11434 for local/general
EXPOSE 11434
# EXPOSE 8080 ; used for single container cloud run

WORKDIR /ollama

COPY start-ollama.sh /ollama/start.sh

RUN chmod +x /ollama/start.sh

ENTRYPOINT [ "/bin/bash" ]

CMD ["/ollama/start.sh"]