FROM ollama/ollama:latest
# EXPOSE 11434  ; used for local
EXPOSE 8080

WORKDIR /ollama

COPY start-ollama.sh /ollama/start.sh

RUN chmod +x /ollama/start.sh

ENTRYPOINT [ "/bin/bash" ]

CMD ["/ollama/start.sh"]